# Welcome to Jekyll!

# Website settings
title: "Psychotherapiepraxis Dipl.-Psych. Eva Heimke"
description: "Psychotherapie Eva Heimke"
keywords: "Psychotherapie, Magdeburg, Tiefenpsychologie, Psychologe, Psychologin, Magdeburg, Eva Heimke, TFP, Psychotherapeutin, psychologische"
baseurl: "/"
url: "http://psychotherapie-heimke.de"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: '/static/img/'

# author
author:
  name: 'Dipl.-Psych. Eva Heimke'
  first_name: 'Eva'
  last_name: 'Heimke'
  email: 'mail@psychotherapie-heimke.de'
#  facebook_username: 'fb_username'
#  github_username: 'github_username'
  head_img: 'static/img/landing/eva_heimke.jpg'

# social link
#jingyu:
#  first_name: 'Yu'
#  last_name: 'Jing'
#  description: 'Painter.'
#  link: 'http://angular.jack003.com'
#  email: '805963294@qq.com'

# landing page
landing:
  home: 'Willkommen'
  about: 'Ãœber mich'
  career: 'Ausbildung und Berufserfahrung'
  therapie: 'Psychotherapie'
  material: 'Material'
  kontakt: 'Kontakt'

# google analytics
#ga:
#  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
